# .github/workflows/ci.yml
name: CI - Pruebas Unitarias

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test